### PR TITLE
Create (safe)settings.yml

### PR DESCRIPTION
**Pull request by ab77**
Org. level `settings.yml`.

There are still `suborg` and `repo` levels to define:
* https://github.com/github/safe-settings/blob/main-enterprise/docs/sample-settings/suborg.yml
* https://github.com/github/safe-settings/blob/main-enterprise/docs/sample-settings/repo.yml

### CODE REVIEW

**Comment by klutchell** [comment]
@ab77 Can we schedule a chat at some point to go through what each of these options does? Some of them are new to me and not obvious from the example config.

**Comment by klutchell** [comment]
Also we should [ENABLE_PR_COMMENT](https://github.com/github/safe-settings?tab=readme-ov-file#env-variables) to see what effect these settings will have.

**Comment by ab77** [comment]
> @ab77 Can we schedule a chat at some point to go through what each of these options does? Some of them are new to me and not obvious from the example config.

tbh, I've taken some wild guesses with most of them, since I didn't find most of the comments in the example config very helpful.

**Comment by klutchell** [comment]
I think most of my confusion comes from expecting [this](https://github.com/github/safe-settings/blob/main-enterprise/docs/sample-settings/settings.yml) to be used as the example, I'm not familiar with the purpose of rulesets.

**Comment by klutchell** [comment]
I don't see the safe settings bot running in the PR checks, are we sure it's enabled on this repo?

**Comment by ab77** [comment]
> I don't see the safe settings bot running in the PR checks, are we sure it's enabled on this repo?

I has no policy right now.

**Comment by klutchell** [comment]
I think if you squash the two commits then LGTM.

Do we want to install the app itself on only one or two repos initially before we try all repos in the org? We can test by changing the settings manually and see if they get reverted (on schedule or with manual run).

**Comment by ab77** [comment]
> I think if you squash the two commits then LGTM.

Do we really care about the squash/rebase ceremony, especially in playground/experimental repos?

**Comment by ab77** [comment]
> Do we want to install the app itself on only one or two repos initially before we try all repos in the org? We can test by changing the settings manually and see if they get reverted (on schedule or with manual run).

I've set it [here](https://github.com/organizations/balena-io-experimental/settings/installations/45044054)

image

Going forward, we have one of these already installed in product-os:

(main) https://github.com/organizations/product-os/settings/apps/product-os-safe-settings
(install) https://github.com/organizations/product-os/settings/installations/42278744

Once thing we need to agree on is where the `main` app installs live, since we only need one place/config from which to install them into other orgs (unless the config needs to be different between installations).

**Comment by klutchell** [comment]
> Do we really care about the squash/rebase ceremony, especially in playground/experimental repos?

absolutely

**Comment by ab77** [comment]
> > Do we really care about the squash/rebase ceremony, especially in playground/experimental repos?
> 
> absolutely

what's the reasoning behind this?

**Comment by klutchell** [comment]
I disagree that clean commit history is a ceremony, and not simply good process and habit regardless of environment and audience. I would much prefer we all get into the habit of running `git commit --amend` rather than `git commit` if we have a change to the previous commit.

**Comment by ab77** [comment]
> Yeah, I was thinking we would use that product-os one for our main app and install it on other orgs from there. I hope the app config does not need to differ between orgs.

We'll need to update the private key, but that's trivial.

**Comment by ab77** [comment]
lgtm

**Pull request merged**
